[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_with = "3.12.0"
chrono = "0.4.40"