[package]
name = "warheads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thirtyfour = "0.35"  # Selenium WebDriver library for Rust
tokio = { version = "1", features = ["full"] }  # Async runtime
dapi = { path = "dapi", version = "0.1.0" }