[package]
name = "corrections"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
stats = { path = "../stats", version = "0.1.0"}
dapi = { path = "../dapi", version = "0.1.0"}
once_cell = "1.20.2"
serde_json = "1.0.133"