use tokio::io;

use crate::format::path_manager::nba_prediction_file;
use crate::stats::prediction::Prediction;

use crate::storage::write::write_serializable_with_directory;
use crate::types::GameDate;

use std::collections::HashMap;

// write the predictions generated by the prediction engine to date based files
pub fn write_predictions(predictions: Vec<Prediction>) -> Result<(), io::Error> {
    let mut date_map = HashMap::<GameDate, Vec<Prediction>>::new();

    for prediction in predictions {
        date_map
            .entry(prediction.date())
            .or_insert_with(Vec::new)
            .push(prediction);
    }

    for (date, predictions) in date_map {
        write_serializable_with_directory(&nba_prediction_file(date), &predictions)?;
    }

    Ok(())
}
