[package]
name = "stats"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
derive_builder = "0.20.2"
time = { version = "0.3.37", features = ["serde"] }
