pub mod cdf;
pub mod cost;
pub mod elo;
pub mod elo_tracker;
mod elo_writer;
pub mod log_loss;
pub mod measurement;
pub mod model;
pub mod nelder_mead;
mod simplex;
mod tests;
mod training_set;
mod vector;
