pub mod cdf;
pub mod cost;
pub mod elo;
pub mod gradient_descent;
pub mod linear_regression;
pub mod log_loss;
pub mod logisitic_regression;
pub mod model;
pub mod models;
pub mod nelder_mead;
pub mod observation;
mod simplex;
mod tests;
mod training_set;
mod vector;
